#!/bin/bash
# Initialize repo-refresh progress tracking in a project
# Run this once per project to set up the directory structure

set -euo pipefail

PROJECT_DIR="${1:-.}"
PROGRESS_DIR="$PROJECT_DIR/.claude/progress"

echo "🔄 Initializing repo-refresh progress tracking..."

# Create directory structure
mkdir -p "$PROGRESS_DIR"

# Create initial summaries file
if [ ! -f "$PROGRESS_DIR/summaries.md" ]; then
    cat > "$PROGRESS_DIR/summaries.md" << 'EOF'
# Session Summaries

_Brief notes from each work session. Most recent entries at top._
_Generated by repo-refresh plugin - helps Claude pick up where you left off._

---

EOF
    echo "✅ Created summaries.md"
fi

# Add to .gitignore if it exists (progress logs are personal/ephemeral)
if [ -f "$PROJECT_DIR/.gitignore" ]; then
    if ! grep -q ".claude/progress" "$PROJECT_DIR/.gitignore" 2>/dev/null; then
        echo "" >> "$PROJECT_DIR/.gitignore"
        echo "# Claude progress logs (repo-refresh plugin)" >> "$PROJECT_DIR/.gitignore"
        echo ".claude/progress/" >> "$PROJECT_DIR/.gitignore"
        echo "✅ Added .claude/progress/ to .gitignore"
    fi
fi

# Create a README in the progress dir
cat > "$PROGRESS_DIR/README.md" << 'EOF'
# Progress Logs

This directory contains auto-generated progress notes from the `repo-refresh` Claude Code plugin.

## Files

- `summaries.md` - Session summaries (written on session end)
- `YYYY-MM-DD.md` - Daily file activity logs

## Purpose

When you run `/repo-refresh`, Claude reads these logs to understand:
- What was worked on recently
- Decisions that were made
- Planned next steps

This makes starting a new session feel like picking up mid-conversation rather than starting cold.

## Note

These files are typically gitignored since they're personal working notes, not project artifacts.
EOF

echo "✅ Created README.md"
echo ""
echo "📁 Progress tracking initialized at: $PROGRESS_DIR"
echo ""
echo "Usage:"
echo "  /repo-refresh  - Get caught up on where you left off"
echo "  /progress      - View recent progress or add manual notes"
echo ""
echo "Progress notes are automatically created when:"
echo "  - You edit/write files (logged to daily file)"
echo "  - Sessions end (summary added to summaries.md)"
