#!/bin/bash
set -euo pipefail

# Progress logger for repo-refresh plugin
# Runs on PostToolUse for Write|Edit tools - captures actual file work
# Creates meaningful progress breadcrumbs for future sessions

PROGRESS_DIR="${CLAUDE_PROJECT_DIR:-.}/.claude/progress"
PROGRESS_FILE="$PROGRESS_DIR/$(date +%Y-%m-%d).md"
TIMESTAMP=$(date "+%H:%M:%S")

# Create progress directory if it doesn't exist
mkdir -p "$PROGRESS_DIR"

# Read the hook input
INPUT=$(cat)

# Extract what tool was used and on what file
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // "unknown"' 2>/dev/null || echo "unknown")
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // "unknown"' 2>/dev/null || echo "unknown")

# Only log meaningful file operations
if [ "$FILE_PATH" = "unknown" ] || [ "$FILE_PATH" = "null" ]; then
    exit 0
fi

# Create today's log if it doesn't exist
if [ ! -f "$PROGRESS_FILE" ]; then
    cat > "$PROGRESS_FILE" << EOF
# Progress Log - $(date +%Y-%m-%d)

_Auto-generated by repo-refresh plugin. These notes help Claude pick up where you left off._

---

EOF
fi

# Extract just the filename for cleaner logs
FILENAME=$(basename "$FILE_PATH")

# Append the progress entry
echo "- \`$TIMESTAMP\` **$TOOL_NAME** → \`$FILENAME\`" >> "$PROGRESS_FILE"

# Cleanup: keep file manageable (last 200 entries max)
LINE_COUNT=$(wc -l < "$PROGRESS_FILE")
if [ "$LINE_COUNT" -gt 250 ]; then
    # Keep header (first 7 lines) + last 200 entries
    head -7 "$PROGRESS_FILE" > "$PROGRESS_FILE.tmp"
    tail -200 "$PROGRESS_FILE" >> "$PROGRESS_FILE.tmp"
    mv "$PROGRESS_FILE.tmp" "$PROGRESS_FILE"
fi

exit 0
